### ISSUE TITLE
Does not compile with LLVM/clang

### ISSUE THREAD

**Issue by tpgxyz** [rhinstaller/efivar#47]
Hi,
version 0.23 does not compile with LLVM/clang-3.8.0

+ /usr/bin/make -j8 -O libdir=/usr/lib64 bindir=/usr/bin mandir=/usr/share/man 'ccldflag=-Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -flto -Wl,-O2  -Wl,--no-undefined -flto ' V=1 -j1
make[1]: Entering directory '/builddir/build/BUILD/efivar-0.23/src'
/usr/bin/clang -Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -flto -I/builddir/build/BUILD/efivar-0.23/src/include/efivar/    -L.  -Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -flto -Wl,-O2  -Wl,--no-undefined -flto     -DEFIVAR_BUILD_ENVIRONMENT -o makeguids makeguids.c guid.c -ldl 
/builddir/build/BUILD/efivar-0.23/Make.rules:13: recipe for target 'makeguids' failed
make[1]: Leaving directory '/builddir/build/BUILD/efivar-0.23/src'
Makefile:10: recipe for target 'all' failed
In file included from makeguids.c:26:
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:86:16: warning: unknown attribute '__artificial__' ignored [-Wunknown-attributes]
__attribute__((__artificial__))
               ^
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:92:6: error: use of unknown builtin '__builtin_va_arg_pack_len' [-Wimplicit-function-declaration]
        if (__builtin_va_arg_pack_len() != 0 &&
            ^
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:103:20: error: use of unknown builtin '__builtin_va_arg_pack' [-Wimplicit-function-declaration]
                                          attributes, __builtin_va_arg_pack());
                                                      ^
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:103:20: note: did you mean '__builtin_va_arg_pack_len'?
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:92:6: note: '__builtin_va_arg_pack_len' declared here
        if (__builtin_va_arg_pack_len() != 0 &&
            ^
1 warning and 2 errors generated.
In file included from guid.c:23:
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:86:16: warning: unknown attribute '__artificial__' ignored [-Wunknown-attributes]
__attribute__((__artificial__))
               ^
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:92:6: error: use of unknown builtin '__builtin_va_arg_pack_len' [-Wimplicit-function-declaration]
        if (__builtin_va_arg_pack_len() != 0 &&
            ^
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:103:20: error: use of unknown builtin '__builtin_va_arg_pack' [-Wimplicit-function-declaration]
                                          attributes, __builtin_va_arg_pack());
                                                      ^
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:103:20: note: did you mean '__builtin_va_arg_pack_len'?
/builddir/build/BUILD/efivar-0.23/src/include/efivar/efivar.h:92:6: note: '__builtin_va_arg_pack_len' declared here
        if (__builtin_va_arg_pack_len() != 0 &&
            ^
guid.c:61:8: warning: implicit declaration of function 'asprintf' is invalid in C99 [-Wimplicit-function-declaration]
                rc = asprintf(&ret, GUID_FORMAT,
                     ^
2 warnings and 2 errors generated.
make[1]: *** [makeguids] Error 1
make: *** [all] Error 2
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.42846 (%build)
    Bad exit status from /var/tmp/rpm-tmp.42846 (%build)
Child returncode was: 1
EXCEPTION: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb  --target x86_64 --without uclibc --nodeps builddir/build/SPECS/efivar.spec']
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock_urpm/trace_decorator.py", line 70, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mock_urpm/util.py", line 402, in do
    raise mock_urpm.exception.Error, ("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb  --target x86_64 --without uclibc --nodeps builddir/build/SPECS/efivar.spec']
LEAVE do --> EXCEPTION RAISED

**Comment by amagnasco** [comment]
same on arch 'armv7h'

**Comment by vathpela** [comment]
Well, we no longer use __builtin_va_arg_pack_len() and friends, so that should be fixed in 0.24.  Unfortunately, to phase those out, we need real symbol versioning support, which llvm appears to have decided not to implement: https://llvm.org/bugs/show_bug.cgi?id=23231 .

So it probably still will not work, because the compiler is flat out broken.

**Comment by tpgxyz** [comment]
BTW with LLVM/clang-7.0 efivar compiles fine
