### PR TITLE
Fix some warnings caught by -Werror=format-security

### PR DESCRIPTION
**Pull request by superm1**
These were introduced in 8910f45.

Build snippet:

```
gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/home/test/src/efivar/src/include/efivar/  -specs=/home/test/src/efivar/gcc.specs  -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -c -o linux.o linux.c
linux.c: In function ‘sysfs_test_nvme’:
linux.c:155:42: error: unused parameter ‘size’ [-Werror=unused-parameter]
 sysfs_test_nvme(const char *buf, ssize_t size)
                                          ^
linux.c: In function ‘sysfs_parse_nvme’:
linux.c:264:29: error: unused parameter ‘psize’ [-Werror=unused-parameter]
   const char *pbuf, ssize_t psize, ssize_t *poff,
                             ^
linux.c: In function ‘make_blockdev_path’:
linux.c:668:52: error: unused parameter ‘fd’ [-Werror=unused-parameter]
 make_blockdev_path(uint8_t *buf, ssize_t size, int fd, struct disk_info *info)
                                                    ^
cc1: all warnings being treated as errors
```

As far as I can tell no one is actually using make_blockdev_path outside of efivar.

### CODE REVIEW

**Comment by vathpela** [comment]
f108835 is obsoleted by efe8acb7.
